### ISSUE TITLE
Support loading vocabularies with different URI

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#49]
https://uri.gbv.de/terminology/etiras/ does not resolve because at the moment, the vocabulary has a different URI, but `http://uri.gbv.de/terminology/etiras/` is one if its `identifiers`, see https://api.dante.gbv.de/voc?uri=http://uri.gbv.de/terminology/etiras/

The proxy should better redirect https://uri.gbv.de/terminology/etiras/ to https://uri.gbv.de/terminology/http%3A%2F%2Fet-iblk.org%2Fscheme%2F/ in this case.

Note the the underlying DANTE record is going to be changed, so this example won't be relevant in the future but it may apply to other vocabularies.

**Comment by stefandesu** [comment]
> [uri.gbv.de/terminology/etiras](https://uri.gbv.de/terminology/etiras/) does not resolve because at the moment, the vocabulary has a different URI, but `http://uri.gbv.de/terminology/etiras/` is one if its `identifiers`, see [api.dante.gbv.de/voc?uri=http://uri.gbv.de/terminology/etiras/](https://api.dante.gbv.de/voc?uri=http://uri.gbv.de/terminology/etiras/)

When I open the record, it does NOT have `http://uri.gbv.de/terminology/etiras/` as one of its identifiers, only the BARTOC URI. 🤔

**Comment by stefandesu** [comment]
I just tested it locally and if `http://uri.gbv.de/terminology/etiras/` were in `identifier`, it would resolve as expected. We are using `jskos.compare` instead of comparing the URI directly. There would be no redirect, but I don't see that as an issue if the vocabulary does indeed have a http://uri.gbv.de/terminology/ URI.
